apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: demo-workflow
spec:
  entrypoint: get-user-data
  templates:
    - name: get-user-data
      steps:
        - - name: get-user-ids
            template: get-user-ids
        - - name: transform-user-ids-to-objects
            template: transform-user-ids-to-objects
            arguments:
              parameters:
                - name: user-ids
                  value: "{{steps.get-user-ids.outputs.parameters.user-ids}}"
    - name: get-user-ids
      container:
        image: busybox:latest
        command: ["sh", "-c"]
        args: ["echo '[1,2,3]' > /tmp/user-ids"]
      outputs:
        parameters:
          - name: user-ids
            valueFrom:
              path: /tmp/user-ids
    - name: transform-user-ids-to-objects
      inputs:
        parameters:
          - name: user-ids
      container:
        image: alpine:latest
        command: ["sh", "-c"]
        args:
          - |
            apk add jq
            echo "{{inputs.parameters.user-ids}}" | jq ".[] | {id: ., name: \"User \(.)\"}" > /tmp/users
      outputs:
        parameters:
          - name: users
            valueFrom:
              path: /tmp/users
