apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations: &ref_0
    sealedsecrets.bitnami.com/cluster-wide: 'true'
    nethopper.io/controlled: 'true'
    nethopper.io/controlled-type: iac
    nethopper.io/provider-key: AWS
    nethopper.io/provider-name: AWS
    nethopper.io/generated-at: '2025-01-29T22:41:31+05:30'
    nethopper.io/generator-version: v6.0.0-c924336c07
  name: awsconf
  namespace: default
spec:
  encryptedData:
    awsconf: >-
      AgCNzcvDXoadK4egRvKJjAmc4cT/NTkMDmJRws11XN2nl6gXE0x7eeeHshjYYqX97+T/bk9+aFvHu0k7Aobfsxkrju+Hg+ZIALbQI34MKeRxckT9j5rx9WROME/CYBAfpDA1CNbSOL6+LG981ZRVYqNLuHUY4V+MvfTIsPPkbQ12/9eE0UYqVU0JIeZML8PEMo3hnQLtr9tJyN6X4mg/zzKElpZ7kVVhJ2SSMczi0WAH4O+Kkn5gvpmTHB8qfiMqGjy1pNFBW857Fc5kkv+YqYd70+nGRsOFd9xtkmi5zicbuzTPTvZejJzYBELk4wxTMCf9IpLeQDnZy2QuJ0aIGa5BkcLvx7rQRkwxPn4iQuThqWfvEi25JhxTpFLWQSgZnLDXta21FYCViOFEv5hZWGcDy0ESItboKlQZVKfPrrE3NZXxu+xCHURBJEGrJyCiqjLs9Ef59I2gno1J836XFrDqu92dY6COIoisnwAbQV9f75TZguamFH4zHUCacM9AvFOjkGfhCmdg/+AwuNthCQBYpl9cqWU2yssDEKmPy3sugUpyk4/NnXc8T58RK4fQsWYK15k+6LlN1fqbxcJLlySEIZUbB/hPt1jPvo5o0aNpLe7g7v9HGwmqOcfIsluKhaQ9cc+Ezda3o7bM3XikYIldwXpQdbdpDV20FJUMWY61ICZIFSeCcZexrxVpZRJW6zocIwsiEMuX0qL+8o8RqmW1FSy0+xsJL17THZ/ORkHVcT7VIDDOscozI/Cji0dFbHP0yEo50PcMrKeCQz84N7LwyQUGOJ+i88Tagjy1BfQwMgjyrV0z3VPDSr0j5bOvd/+huYo1yH8mCCHPbJTXVWpyGSRoe0GGH+PQ2ymNpg==
  template:
    metadata:
      annotations: *ref_0
      name: awsconf
    type: Opaque
