apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations: &ref_0
    sealedsecrets.bitnami.com/cluster-wide: 'true'
    nethopper.io/controlled: 'true'
    nethopper.io/controlled-type: iac
    nethopper.io/iac-provider-key: aws
    nethopper.io/iac-provider-name: AWS
    nethopper.io/generated-at: '2024-06-13T15:15:42+05:30'
    nethopper.io/generator-version: 5.1.0
  name: aws-creds
  namespace: default
spec:
  encryptedData:
    awsconfig: >-
      AgCM/qYBa8UpaxDmrCML8FgdTb1pfLxH7VWiGNUjr8hAmCV0pkwordR3A4ne2TioKZ0rJCGHaYTBRnrFRHdClf+/80+gj9YhN8YmXp5Zp5Npi0oG6ntPbUSiQudr2tXMb/u683iBVflNq1YWwLLH6YSbNJPZW+qUQ0fU6x9EAZ3UwzIAbbswKEbP/7DHeLttJfIPIoYgDAKGRMQwm+cxs4nXgyYQafJuRofIjgn6yoDi1dpL+D9j9ZgAaCFT5tERZoHICxCl5QCZSKgcxjfB0KwB/ZvCKQKWKmP+TE4X/GitaerQ13QrzVdDIR9OB0T4HzuDRM/v+I15UqYo6fFUVJvG1XMq3OPtFnLIm6u+K39z9RT0voZ2ML7WX73ErWhGHJ7zl5fyIIQWMnCv266iTyVJobV0JF90ExSSPKupdUAjrftvx+ZAHm0CPQZWRkhlv6GxEyIhEe3ehvqqhuUCUYWCpnNeVjIMueDG7FGDaA9j0MF0Vb7WQYbfU+oByYfNHbl3QWlIzJrO7EcxIDEGvSYUTuGdOWO3WFSsEg3POW3HcbeQ2OyDm5zJcQrdhP6i2sCtY+MhOY517e8uovgNUmmRvyLRfSPaIWKd7XedyJp6PXOYkZ3pEGkfN8wz6xwzzt1CLW/kKPXQBqgDV++jkPfINK+xZO6X3LyvMXf/P27Itac2S2sqY3nMEll3UoNijkmxWBcZW6S6/YMHDvB3YQWKDjDqPE4KI+YsjC1fjIY5LJ6KZCEgLFMSeU0RVhqrMHYbzvdhFdp2XPq3KPlzOQDGncScuoqZNZWDrGEc7olcRrSexarqprwNM6urGqWbtnWrALtZeLez/cN0a+c8FyKtuNkc
  template:
    metadata:
      annotations: *ref_0
      name: aws-creds
    type: Opaque
