apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations: &ref_0
    sealedsecrets.bitnami.com/cluster-wide: 'true'
    nethopper.io/controlled: 'true'
    nethopper.io/controlled-type: iac
    nethopper.io/iac-provider-key: AWS
    nethopper.io/iac-provider-name: AWS
    nethopper.io/generated-at: '2024-06-10T17:57:17+05:30'
    nethopper.io/generator-version: 6.0.7-beta
  name: aws-credential-new
  namespace: default
spec:
  encryptedData:
    awsconfig: >-
      AgBYpKVcIKKSjhk0AI69NeTzrkg4uW8bN2TMfZmYtNwRUVExOXnThmkypawyh970Rz6f9kt8Q0qnsvcPJleqgjdDjw9NI7j+hC2MRXXjR7iK+QeaMBCaW8WRcLANUtxrgJR6Qadmqvf0ME+zwXSeKwgMX9eiR5UKAyJTXYgS/fZjCPhOYPyMiVaBNjOi4yC4eM5cHc4Lg3Z2+Bjxn6/Wm7XzlH5ot8ug7IYT+GEhEbNmOZ1duOlmphHAH/KloWr84qtwX4QwhNdKcj4khZyUvLtRhJ/sftDJWI1VJ3r2e0qrk4yQ6xnuk0roICwiAbCJlaiJBhLDd6SG9Pb0n6LeTSyKThK2nt3e/QmtMcD2MzxmRn01Sg0B9RnfXlosDnzHBChac0PreR7JFD2h9h3E2BPptLLaEUVnhoEqAv7Z0/9e8FBEoSbr/Tfi4bhjTFcPin7jxoiZl+1RrFV33IkmopbXfKAYEeY8Ce/KOEcI+0XbnXFKb/ZaEKjn+gg/KWBXAkqZErS7OvGoanHcXXe4OsJr6ImRdObcQ0q0dLau2y8KKZ/Gtc844BEPuaZzGnKkv0xoWTz2Ztu4caUsivoaRlmmBMpSQ0u7tm/ktUoXCtw3JOEinwR+l1iWIPksozT6kGyoWLJlgBHQz65f813WD8jzms1deKu4ZmKwRi5TZBhpL2+9A8UTfqr5mQr38wJaboBXk+YJD/yRf4aLHEaBJ5SflbWl/Ki/5B627AVeSjyYJY6TVTy6yHiopvH9tMmgBKDbusQVrb3Mu1NH+K6n9/03zVdT4Vu/mUxXQATk8kj3abGWYBSRH2/vxEvyiH2QpVTyVEm4mlR2Yz9a/KjRQR9TqbEJB3OEoM/wRQY=
  template:
    metadata:
      annotations: *ref_0
      name: aws-credential-new
    type: Opaque
