apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations: &ref_0
    sealedsecrets.bitnami.com/cluster-wide: 'true'
    nethopper.io/controlled: 'true'
    nethopper.io/controlled-type: iac
    nethopper.io/iac-provider-key: aws
    nethopper.io/iac-provider-name: AWS
    nethopper.io/generated-at: '2024-06-13T18:28:32+05:30'
    nethopper.io/generator-version: 5.1.0
  name: aws-creds
  namespace: default
spec:
  encryptedData:
    awsconfig: >-
      AgCT4qdp3hPJk+6S9ZI0nNGDSnG9Vdv+hN9J3/CUO5sNnxyuGJwgGHKeceuP/Fi/nXGMzwqLb2tXA/4bvjE5IBffwGs2+sDIvPnmd3o32b+6bkhYEJBNzDx6YARmrjGZTfDl9ijn7MEbsnDBGYJ2M3TFHAmhzegekwXyjjEP+/oDHSIOaWYMqjOXcD1Kg7iA0QZl3Gvt3xPu8meCtYCARLtj5aQTruMvAs/CoIM/8FQSWqrO4TqVsAM6SPE/h4qXNe3T4H9+BefmiKYsdi27yTAemnPkf9OyjOuqeZnjvAWEuCQe/JdT+7fDtXPBTLicmvAtcnk1LOkvMfHOsfwnDW4sB2FPQQ/IxvY6l19Iwm5pp/xyGo3EmBFWEefiVtxWtR/yAWd2R+Oli6HT6pM9lqUlrA2TvH7d50nnyjvkwL15Lne3LsJ+ad1vl6ppX+Xj+UEt8CjzcuaW9+EqdwBP9gPlbuUnLYZSK+OWKyDJRIMQrqINs+bVwOFmRbL3L3cd+b1w4vMW46255gbje1635LQwaYmmGS9URJX0isGcJ7SDsQMkYZ/llL/jda0MMxWRGkU5Even8OSuhi6WQzbYvv+CMmR/hfaq+5kfKIZSgQmHyS6KnJG9QfLVOPSEGypggxSorvtY99ygP2oeeGDnwzoAY58vSGTG1vrVugupcoahihWSV8gsS375ZggYJxEhb+KMp+LUeCbyf8GW6mm8NdzlCuR/VkPC/Mc2sM3d69aQ/sfSE+sVeUzy7gtBjhFttER31ULboqk7A1jFTxG0lxNdV5hrnLzcHQkhTxxpi6UqjvfuQEsEC7SK3Hz2P9TGG4AASDrHAq+KQwBJ4YaXmu3K8JEN
  template:
    metadata:
      annotations: *ref_0
      name: aws-creds
    type: Opaque
