apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations: &ref_0
    sealedsecrets.bitnami.com/cluster-wide: 'true'
    nethopper.io/controlled: 'true'
    nethopper.io/controlled-type: iac
    nethopper.io/iac-provider-key: AWS
    nethopper.io/iac-provider-name: AWS
    nethopper.io/generated-at: '2024-06-10T15:59:24+05:30'
    nethopper.io/generator-version: 6.0.7-beta
  name: aws-creds
  namespace: default
spec:
  encryptedData:
    awsconf: >-
      AgBA3QMZZ5Bkp27rPdfN6v32YlVxMsbnhU6v7ZMYIhVpVfpSouA3KPZQRuDsCFBdDxIZ3c5JoaeUDLtG1FisGnE6WkrJU2a1DWKa2vklK0ZSzf0OnBAY47Z8HChOgqEc7WQ4ISpVoVmFZBW34NO12lojHtF17CqmQsf7+3n3ynVQTIBVSNDJH/UZQZGQXc7lxwcbjgNMi9AIqAbU0hygyfihMRBv9k7b5s13KqYjXVaza9ho5sm2h3wZTWd1a5MC8AE9ThfkYAQptzoayaueCChBwvvdXVUO0KVnB8ob3sLxxgeEgB1mASlaWXsZimbkQH+7BVZszlaGZYLzJfXl6XfXZIGg8gwyvXwEutNGEFDuIyzGTkqHVKPIX1SEeO4G39EOWHsDPW8oGOOJeUu1PQfnHNO5jTKP69rG98re+IWiMSxo2tJN3LvAkjHo06zJfyRjITTfG2+lFiWf9bTpLRuO3u7EZCUEa6sZLipoh7sLJPl+8yhhQTeCMIqUWM2PFsBxygTR5e9ye81c9CFdDNttI6k7neaXjmb/z29Shz4YnSxjSu+A5xya97utqmyhLPp1+A/vLv639zL7enUgQC1YD+N7NfsaYyvGBsJ5BRmY4pSxj4GxQTRlH35vkMedrpSHi5CUH7rqdVDFP1p14aiFwjm2iLBuDgIofopUyjlHWVgVm7lufH6UEfmKdQn/htfD3p7hq01vBB3LkKvp47j6uO2WQkQ9VyavBTpv2UzKz9LpHCVR5pCNcIrqdgSc/Yx/LoA6HKXrrKIhz4rHGH80EjPo4oNEzk8C3DWmrYrZk3QI4m+KV4zI2ZpfM2s/Zc6lqEN1vyVXpIUjN02Bhoycox6o+erw2sCvopI=
  template:
    metadata:
      annotations: *ref_0
      name: aws-creds
    type: Opaque
